server {
    listen 80;

    location /static/ {
        root /usr/share/nginx/html;
    }

    location / {
        proxy_pass http://backend:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}